<a href="https://colab.research.google.com/github/NiyazovIlia/Lineal_math/blob/lesson-2/%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0_%D1%83%D1%80%D0%BE%D0%BA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4

In [1]:
# матрицы определены: а (если использовать транспонирование), в и г
# Проверка
import numpy as np
a = np.array([[1, 2], [4, 5], [7, 8], [10, 11]])
b = np.array([[1, 2], [4, 5], [7, 8], [10, 11]])
print(f'{np.dot(a,b.T)}\n')

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]])
print(f'{np.dot(a,b)}\n')

a = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10], [10, 11, 12, 13]])
b = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(f'{np.dot(a,b)}\n')

[[  5  14  23  32]
 [ 14  41  68  95]
 [ 23  68 113 158]
 [ 32  95 158 221]]

[[  6  12  18  24  30  36  42  48]
 [ 15  30  45  60  75  90 105 120]
 [ 24  48  72  96 120 144 168 192]
 [ 33  66  99 132 165 198 231 264]
 [  6  12  18  24  30  36  42  48]
 [ 15  30  45  60  75  90 105 120]
 [ 24  48  72  96 120 144 168 192]
 [ 33  66  99 132 165 198 231 264]]

[[ 10  20  30  40]
 [ 22  44  66  88]
 [ 34  68 102 136]
 [ 46  92 138 184]]



Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Сложение получается: $С=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

Умножение получается: $С=\begin{pmatrix}
(1*4)+(-2*0) & (1*-1)+(-2*5)\\ 
(3*4)+(0*0) & (3*-1)+(0*5)
\end{pmatrix}$  $С=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$

In [2]:
# Проверка
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f"Умножение:\n {np.dot(a,b)}")
print(f"Сложение:\n {a+b}")

Умножение:
 [[  4 -11]
 [ 12  -3]]
Сложение:
 [[ 5 -3]
 [ 3  5]]


Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}.$


$3A - 2B + 4C=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
a_new = 3*a
b_new = 2*b
c_new = 4*c
print(f'Результат:\n {a_new-b_new+c_new}')

Результат:
 [[ 11  -5]
 [  9 -12]]


Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A.T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])
b = a.T
print(f'Первый результат:\n {np.dot(a,b)}')
print(f'Второй результат:\n {np.dot(b,a)}')

Первый результат:
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
Второй результат:
 [[45  0]
 [ 0 14]]


Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
import numpy as np
import random
 
 
def multiplication(a,b,line1,column2,line2):
    if column2 == line1:
        result = []
        result_2 = []
        for i in range(line1):
            for j in range(column2):
                s = 0
                for k in range(line2):
                    s = s + a[i][k] * b[k][j]
                result_2.append(s)
            result.append(result_2)
            result_2 = []
        return np.array(result)
 
 
n1 = int(input('Введите количество строк в 1 матрице: '))
m1 = int(input('Введите количество столбцов в 1 матрице: '))
n2 = int(input('Введите количество строк во 2 матрице: '))
m2 = int(input('Введите количество столбцов во 2 матрице: '))
 
matrix1 = [[random.randint(0,10) for i in range(m1)] for j in range(n1)]
matrix2 = [[random.randint(0,10) for k in range(m2)] for l in range(n2)]
 
 
print('1 матрица: ')
print(np.array(matrix1))
print('2 матрица: ')
print(np.array(matrix2))
print('умножение этих матриц: ')
print(multiplication(np.array(matrix1),np.array(matrix2),n1,m2,n2))

Введите количество строк в 1 матрице: 2
Введите количество столбцов в 1 матрице: 3
Введите количество строк во 2 матрице: 3
Введите количество столбцов во 2 матрице: 2
1 матрица: 
[[3 8 9]
 [9 8 9]]
2 матрица: 
[[10  4]
 [ 5  6]
 [ 5 10]]
умножение этих матриц: 
[[115 150]
 [175 174]]


Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [6]:
# определитель в а = (sinx)^2 + (cosx)^2, в б = 180, в с = 6
# проверка
import scipy.linalg

a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

a = np.array([[1, 2, 3], [5, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180
Матрица:
[[1 2 3]
 [5 5 6]
 [7 8 9]]
Определитель:
6


Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$ = 16
    
   б) $det(A^{T})$ = 4 
    
   в) $det(2A)$ = 8

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [7]:
# Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю. Определитель данной матрицы будет равен 0, следовательно из определения
# она вырожденная
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [8]:
# ранг первой матрицы будет равен 2, так как 3 строка является суммой первой и второй
# ранг второй матрицы будет равен 3, так как 3 строка является суммой первой и второй
x = [1,2,3]
y = [1,1,1]
z = [2,3,4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

x = [0,0,2,1]
y = [0,0,2,2]
z = [0,0,4,3]
w = [2,3,5,6]

a = np.array([x, y, z, w])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2
Ранг матрицы: 3
